export const ROUTES = [
  "/",
  "/about",
  "/contact",
  "/resources",
  "/wellbeing",
  "/wellbeing/daily-rituals",
  "/wellbeing/nourish",
  "/wellbeing/restore",
  "/sensory-insights",
  "/members",
  "/terms",
  "/privacy",
  "/blog",
  "/books",
  "/toys",
] as const;
